### ISSUE TITLE
`evm_mine` and `miner_start` don't respect --mode.instamine=eager

### ISSUE THREAD

**Issue by davidmurdoch** [ConsenSys-archive/ganache#2029]
`evm_mine` and `miner_start` shouldn't return until all the blocks have been mined, but they do. Additionally, we need to figure out how to handle subscription timings (newHeads, etc); should they be sent _after_ all blocks have been mined (and thus always after the RPCs complete their return), or after each block?

**Comment by msuscens** [comment]
👍  I suspect this issue breaks the ganache-time-traveller library - which means I'm unable to use Ganache v7 with the project I'm developing as all my truffle tests extensively use TimeTraveller (my tests work fine with Ganache 6).

**Comment by davidmurdoch** [comment]
@msuscens, I believe this was _mostly_ fixed in https://github.com/trufflesuite/ganache/commit/c32aee8aad4ab5357c54eb5f45383316c844ceda, but we've since discovered a race condition that can cause some issues. We have a PR in progress to solve this race condition here: https://github.com/trufflesuite/ganache/pull/3016

**Comment by MicaiahReid** [comment]
@davidmurdoch, #3016 should have fixed this. I can add tests to make sure of this.

In terms of subscription timings, we fire those off as they are ready rather than waiting for all blocks to be mined. Do you think that's a problem? I don't think we know what the preferred behavior would be, I'd vote not to hold up this issue and to leave as is. Maybe we could also put up a poll in the GitHub Discussions for what the expected behavior would be?

**Comment by msuscens** [comment]
> @msuscens, I believe this was _mostly_ fixed in [c32aee8](https://github.com/trufflesuite/ganache/commit/c32aee8aad4ab5357c54eb5f45383316c844ceda), but we've since discovered a race condition that can cause some issues. We have a PR in progress to solve this race condition here: #3016

@davidmurdoch I've tried again under v7.3.1 but I still get the same issue when advancing time:  I've described the issue in full here: https://github.com/trufflesuite/ganache/discussions/3264

Is being unable to correctly advance time being caused by this issue?  Or is it another issue - in which case shall I create a new issue (from my discussion post)?
